// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Va8hPzwbJPpmcCtgc8rg1bEYxSyghFQ',
    appId: '1:383950845514:web:645d991ea5a52db7bf98b3',
    messagingSenderId: '383950845514',
    projectId: 'autophile-13aa3',
    authDomain: 'autophile-13aa3.firebaseapp.com',
    storageBucket: 'autophile-13aa3.firebasestorage.app',
    measurementId: 'G-T7B1CNRT2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAOzXg_pOVh9g9HIg-fbS9qL-ncTuYVGg',
    appId: '1:383950845514:android:aa8f02946b8d22c3bf98b3',
    messagingSenderId: '383950845514',
    projectId: 'autophile-13aa3',
    storageBucket: 'autophile-13aa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp1es4Y6phLayOKtxyk-VAXUrO68Gu2Ug',
    appId: '1:383950845514:ios:039674138e772a82bf98b3',
    messagingSenderId: '383950845514',
    projectId: 'autophile-13aa3',
    storageBucket: 'autophile-13aa3.firebasestorage.app',
    iosBundleId: 'com.example.autophile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp1es4Y6phLayOKtxyk-VAXUrO68Gu2Ug',
    appId: '1:383950845514:ios:039674138e772a82bf98b3',
    messagingSenderId: '383950845514',
    projectId: 'autophile-13aa3',
    storageBucket: 'autophile-13aa3.firebasestorage.app',
    iosBundleId: 'com.example.autophile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1Va8hPzwbJPpmcCtgc8rg1bEYxSyghFQ',
    appId: '1:383950845514:web:1a74ee765c6015e9bf98b3',
    messagingSenderId: '383950845514',
    projectId: 'autophile-13aa3',
    authDomain: 'autophile-13aa3.firebaseapp.com',
    storageBucket: 'autophile-13aa3.firebasestorage.app',
    measurementId: 'G-4WTYNMD7W9',
  );
}
